#!/usr/bin/env python3
"""Bundle the real pure-Python modules into the demo site (zero drift).

The interactive page runs the ACTUAL AEGIS control/safety code via Pyodide.
Rather than hand-copy (and risk drift), this regenerates
``docs/site/aegis_modules.js`` straight from ``src/aegis`` whenever the source
changes. Only the dependency-free modules are bundled (no torch/cv2):

    tracker.py  controller.py  simulator.py  safety.py

Run: python tools/build_site.py
"""

from __future__ import annotations

import json
import os

SRC = "src/aegis"
MODULES = ["tracker.py", "controller.py", "simulator.py", "safety.py"]
OUT = "docs/site/aegis_modules.js"


def main() -> None:
    bundle = {"aegis/__init__.py": ""}
    for name in MODULES:
        with open(os.path.join(SRC, name), encoding="utf-8") as f:
            bundle[f"aegis/{name}"] = f.read()

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by tools/build_site.py — do not edit.\n")
        f.write("// The interactive demo runs these exact modules via Pyodide.\n")
        f.write("window.AEGIS_MODULES = ")
        json.dump(bundle, f, ensure_ascii=False, indent=0)
        f.write(";\n")
    total = sum(len(v) for v in bundle.values())
    print(f"Wrote {OUT}  ({len(bundle)} modules, {total} chars)")


if __name__ == "__main__":
    main()
