#!/usr/bin/env python3
"""Export the from-scratch CNN for the in-browser demo.

Trains the discriminator, then writes two files the demo loads:
  docs/site/cnn_weights.js  — trained weights (window.CNN_WEIGHTS)
  docs/site/cnn_conv.js      — the pure-NumPy conv source (window.CNN_CONV_SRC)

The demo runs *this exact* conv code (cnn/conv.py) in Pyodide with these
weights, so the browser classifier is the real from-scratch CNN.

Run: python tools/export_cnn.py
"""

from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, "src")

OUT = "docs/site"


def _round(obj, nd=4):
    if isinstance(obj, list):
        return [_round(o, nd) for o in obj]
    return round(obj, nd)


def main() -> None:
    import torch
    from torch import nn, optim

    from aegis.cnn.model import build_net
    from aegis.cnn.patches import make_dataset

    Xtr, ytr = make_dataset(2000, seed=1)
    Xva, yva = make_dataset(400, seed=99)
    Xtr, ytr = torch.tensor(Xtr), torch.tensor(ytr)
    Xva, yva = torch.tensor(Xva), torch.tensor(yva)

    net = build_net()
    opt = optim.Adam(net.parameters(), lr=1e-3)
    loss_fn = nn.CrossEntropyLoss()
    print("training discriminator for export...")
    for epoch in range(14):
        perm = torch.randperm(len(Xtr))
        for i in range(0, len(Xtr), 64):
            idx = perm[i:i + 64]
            opt.zero_grad(); loss_fn(net(Xtr[idx]), ytr[idx]).backward(); opt.step()
    net.eval()
    with torch.no_grad():
        acc = (net(Xva).argmax(1) == yva).float().mean().item()
    print(f"  val accuracy {acc*100:.1f}%")

    weights = {
        "conv1_w": net[0].weight, "conv1_b": net[0].bias,
        "conv2_w": net[3].weight, "conv2_b": net[3].bias,
        "fc1_w": net[7].weight, "fc1_b": net[7].bias,
        "fc2_w": net[9].weight, "fc2_b": net[9].bias,
    }
    payload = {k: _round(v.detach().cpu().numpy().tolist()) for k, v in weights.items()}

    os.makedirs(OUT, exist_ok=True)
    with open(f"{OUT}/cnn_weights.js", "w") as f:
        f.write("// AUTO-GENERATED by tools/export_cnn.py — trained weights.\n")
        f.write("window.CNN_WEIGHTS = ")
        json.dump(payload, f)
        f.write(";\n")

    with open("src/aegis/cnn/conv.py", encoding="utf-8") as f:
        conv_src = f.read()
    with open(f"{OUT}/cnn_conv.js", "w") as f:
        f.write("// AUTO-GENERATED by tools/export_cnn.py — the real conv.py source.\n")
        f.write("window.CNN_CONV_SRC = ")
        json.dump(conv_src, f)
        f.write(";\n")

    sz = os.path.getsize(f"{OUT}/cnn_weights.js") / 1024
    print(f"wrote {OUT}/cnn_weights.js ({sz:.0f} KB) and cnn_conv.js")


if __name__ == "__main__":
    main()
